# Uncomment this line to define a global platform for your project
# platform :ios, '7.0'

target 'CustomTabBar' do
pod 'MHCustomTabBarController-parent', '~> 1.3'
end

target 'CustomTabBarTests' do

end

